DEFAULT_BRANCH: develop
APPLY_FIXES: all
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_MISSPELL
ENABLE_LINTERS:
  - PYTHON_FLAKE8
  - PYTHON_BLACK
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
  - JSON_PRETTIER
  - ENV_DOTENV_LINTER
  - SQL_SQL_LINT

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false

CONSOLE_REPORTER: true
TEXT_REPORTER: true
SARIF_REPORTER: false