"""init

Revision ID: 2e89c3c5b30d
Revises: 
Create Date: 2025-09-30 23:49:08.138553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e89c3c5b30d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Create enum type first
    blog_status = sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='blogstatus')
    blog_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('blogs', sa.Column('excerpt', sa.String(length=150), nullable=True))
    op.add_column('blogs', sa.Column('status', blog_status, nullable=False))
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('mimetype', sa.String(length=100), nullable=False))
    op.drop_column('documents', 'file_path')
    op.add_column('mpesa_transactions', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.add_column('mpesa_transactions', sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('response_code', sa.String(length=10), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('response_description', sa.Text(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('customer_message', sa.Text(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('result_code', sa.String(length=10), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('result_desc', sa.Text(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('transaction_date', sa.String(length=50), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('callback_received', sa.Boolean(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('raw_callback_data', sa.JSON(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.alter_column('mpesa_transactions', 'transaction_code',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('mpesa_transactions', 'paid_by',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_unique_constraint(None, 'mpesa_transactions', ['checkout_request_id'])
    op.create_foreign_key(None, 'mpesa_transactions', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_constraint(None, 'mpesa_transactions', type_='foreignkey')
    op.drop_constraint(None, 'mpesa_transactions', type_='unique')
    op.alter_column('mpesa_transactions', 'paid_by',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('mpesa_transactions', 'transaction_code',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('mpesa_transactions', 'invoice_id')
    op.drop_column('mpesa_transactions', 'raw_callback_data')
    op.drop_column('mpesa_transactions', 'callback_received_at')
    op.drop_column('mpesa_transactions', 'callback_received')
    op.drop_column('mpesa_transactions', 'status')
    op.drop_column('mpesa_transactions', 'transaction_date')
    op.drop_column('mpesa_transactions', 'mpesa_receipt_number')
    op.drop_column('mpesa_transactions', 'result_desc')
    op.drop_column('mpesa_transactions', 'result_code')
    op.drop_column('mpesa_transactions', 'customer_message')
    op.drop_column('mpesa_transactions', 'response_description')
    op.drop_column('mpesa_transactions', 'response_code')
    op.drop_column('mpesa_transactions', 'checkout_request_id')
    op.drop_column('mpesa_transactions', 'merchant_request_id')
    op.drop_column('mpesa_transactions', 'phone_number')
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('documents', 'mimetype')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'file_data')
    op.drop_column('documents', 'title')
    op.drop_column('blogs', 'status')
    op.drop_column('blogs', 'excerpt')
    # Drop enum type last
    sa.Enum(name='blogstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
