"""added table for funding and partnership module

Revision ID: 44336df75e28
Revises: 3d67fb05c1d4
Create Date: 2026-09-22 06:06:59.969777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44336df75e28'
down_revision = '3d67fb05c1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships_n_funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('funding', 'partnership', name='partnershiptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('image_content_type', sa.String(length=50), nullable=False),
    sa.Column('launch_date', sa.DateTime(), nullable=False),
    sa.Column('deadline_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'published', 'rejected', 'archived', name='partnershipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnerships_n_funding')
    # ### end Alembic commands ###
