"""added soft delete column

Revision ID: 52bab2717501
Revises: cb1357822cc1
Create Date: 2025-10-06 22:59:10.277475
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bab2717501'
down_revision = 'cb1357822cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted column to bookings table
    op.add_column('bookings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE bookings SET is_deleted = FALSE')
    op.alter_column('bookings', 'is_deleted', nullable=False)

    # Add is_deleted column to services table
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE services SET is_deleted = FALSE')
    op.alter_column('services', 'is_deleted', nullable=False)

    # Add is_deleted column to tickets table
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE tickets SET is_deleted = FALSE')
    op.alter_column('tickets', 'is_deleted', nullable=False)

    # Add is_deleted column to users table
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_deleted = FALSE')
    op.alter_column('users', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('tickets', 'is_deleted')
    op.drop_column('services', 'is_deleted')
    op.drop_column('bookings', 'is_deleted')
    # ### end Alembic commands ###