"""Update Document model to store binary file data

Revision ID: 549a3c3891a8
Revises: 922f86e86a6d
Create Date: 2025-09-30 11:44:55.207413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549a3c3891a8'
down_revision = '922f86e86a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('mimetype', sa.String(length=100), nullable=False))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('documents', 'mimetype')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'file_data')
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
