"""added soft delete column invoice

Revision ID: 685ff26d2050
Revises: 52bab2717501
Create Date: 2025-10-06 23:45:25.379183

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "685ff26d2050"
down_revision = "52bab2717501"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the column as nullable first
    op.add_column("invoices", sa.Column("is_deleted", sa.Boolean(), nullable=True))

    # Step 2: Set default value for existing rows
    op.execute("UPDATE invoices SET is_deleted = FALSE")

    # Step 3: Alter column to make it non-nullable
    op.alter_column("invoices", "is_deleted", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "is_deleted")
    # ### end Alembic commands ###
