"""changed the values of admin id

Revision ID: 83a05d63a677
Revises: dd2a386eeb0c
Create Date: 2025-10-13 11:10:20.004702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83a05d63a677'
down_revision = 'dd2a386eeb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE role_enum " \
                "USING role::text::role_enum;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     # Assign NULL admin_id tickets to a default admin before making column non-nullable
    op.execute("""
        UPDATE tickets
        SET admin_id = (SELECT id FROM users WHERE role = 'ADMIN' LIMIT 1)
        WHERE admin_id IS NULL
    """)
    op.alter_column('users', 'role',
                    existing_type=sa.Enum('CLIENT', 'ADMIN', 'SUPER_ADMIN', name='role_enum'),
                    type_=postgresql.ENUM('CLIENT', 'ADMIN', 'SUPER_ADMIN', name='role_enum_old'),
                    existing_nullable=False)
    op.alter_column('tickets', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
