"""add content type to blog image

Revision ID: 922f86e86a6d
Revises: de2b07347ef5
Create Date: 2025-09-27 12:43:43.915964

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "922f86e86a6d"
down_revision = "de2b07347ef5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blogs",
        sa.Column(
            "image_content_type",
            sa.String(length=50),
            nullable=False,
            server_default="image/jpeg",
        ),
    )
    op.alter_column("blogs", "image_content_type", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blogs", "image_content_type")
    # ### end Alembic commands ###
