"""Add excerpt column

Revision ID: a4500c7eaa07
Revises: 922f86e86a6d
Create Date: 2025-09-30 08:38:03.245378

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4500c7eaa07"
down_revision = "922f86e86a6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blogs", sa.Column("excerpt", sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blogs", "excerpt")
    # ### end Alembic commands ###
