"""Update tokens table

Revision ID: a72acb425c5e
Revises: cea4d948af0d
Create Date: 2025-09-26 12:24:08.658699

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a72acb425c5e"
down_revision = "cea4d948af0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tokens", "value", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "tokens",
        "expiry_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.create_index(op.f("ix_tokens_value"), "tokens", ["value"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_value"), table_name="tokens")
    op.alter_column(
        "tokens",
        "expiry_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column("tokens", "value", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
