"""Initial fresh migration

Revision ID: b0ececea6571
Revises: 
Create Date: 2025-10-06 21:52:12.286141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ececea6571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('mpesa_transaction_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('cash_transaction_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('card_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'mpesa_transactions', ['mpesa_transaction_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'card_transactions', ['card_transaction_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'cash_transactions', ['cash_transaction_id'], ['id'])
    op.drop_column('payments', 'payment_method_id')
    op.add_column('services', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('services', sa.Column('image', sa.LargeBinary(), nullable=False))
    op.add_column('services', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('services', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('services', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('services', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('services', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('services', 'status')
    op.drop_column('services', 'image')
    op.drop_column('services', 'title')
    op.add_column('payments', sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'card_transaction_id')
    op.drop_column('payments', 'cash_transaction_id')
    op.drop_column('payments', 'mpesa_transaction_id')
    op.drop_table('card_transactions')
    # ### end Alembic commands ###
