"""add MPESA callback fields to Payment

Revision ID: bc4d5c7c607e
Revises: 7607965119bd
Create Date: 2025-09-29 22:32:24.520812

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bc4d5c7c607e"
down_revision = "7607965119bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesa_transactions",
        sa.Column("merchant_request_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("checkout_request_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("response_code", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("response_description", sa.Text(), nullable=True),
    )
    op.add_column(
        "mpesa_transactions", sa.Column("customer_message", sa.Text(), nullable=True)
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("result_code", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "mpesa_transactions", sa.Column("result_desc", sa.Text(), nullable=True)
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("mpesa_receipt_number", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("transaction_date", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column(
            "status", sa.String(length=50), nullable=True, server_default="pending"
        ),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("callback_received", sa.Boolean(), nullable=True, server_default="0"),
    )
    op.add_column(
        "mpesa_transactions",
        sa.Column("callback_received_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "mpesa_transactions", sa.Column("raw_callback_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "mpesa_transactions", sa.Column("invoice_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "mpesa_transactions",
        "transaction_code",
        existing_type=sa.VARCHAR(length=15),
        nullable=True,
    )
    op.create_unique_constraint(None, "mpesa_transactions", ["checkout_request_id"])
    op.create_foreign_key(
        None, "mpesa_transactions", "invoices", ["invoice_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mpesa_transactions", type_="foreignkey")
    op.drop_constraint(None, "mpesa_transactions", type_="unique")
    op.alter_column(
        "mpesa_transactions",
        "transaction_code",
        existing_type=sa.VARCHAR(length=15),
        nullable=False,
    )
    op.drop_column("mpesa_transactions", "invoice_id")
    op.drop_column("mpesa_transactions", "raw_callback_data")
    op.drop_column("mpesa_transactions", "callback_received_at")
    op.drop_column("mpesa_transactions", "callback_received")
    op.drop_column("mpesa_transactions", "status")
    op.drop_column("mpesa_transactions", "transaction_date")
    op.drop_column("mpesa_transactions", "mpesa_receipt_number")
    op.drop_column("mpesa_transactions", "result_desc")
    op.drop_column("mpesa_transactions", "result_code")
    op.drop_column("mpesa_transactions", "customer_message")
    op.drop_column("mpesa_transactions", "response_description")
    op.drop_column("mpesa_transactions", "response_code")
    op.drop_column("mpesa_transactions", "checkout_request_id")
    op.drop_column("mpesa_transactions", "merchant_request_id")
    # ### end Alembic commands ###
