"""change blog image type to large binary

Revision ID: de2b07347ef5
Revises: f6448c0964f2
Create Date: 2025-09-27 11:48:48.209850

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de2b07347ef5"
down_revision = "f6448c0964f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blogs",
        "image",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="image::bytea",
    )
    op.drop_constraint(op.f("uq_tokens_value"), "tokens", type_="unique")
    op.create_index(op.f("ix_tokens_value"), "tokens", ["value"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_value"), table_name="tokens")
    op.create_unique_constraint(
        op.f("uq_tokens_value"),
        "tokens",
        ["value"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "blogs",
        "image",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
