"""Paid by not mandatory

Revision ID: ebcd82aeaf5b
Revises: 6cda6b04a6b4
Create Date: 2025-09-30 14:16:04.354667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcd82aeaf5b'
down_revision = '6cda6b04a6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'paid_by',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mpesa_transactions', 'paid_by',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
