"""Add status column to blog

Revision ID: f566361e4f48
Revises: a4500c7eaa07
Create Date: 2025-09-30 09:27:38.076769

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f566361e4f48"
down_revision = "a4500c7eaa07"
branch_labels = None
depends_on = None

# Define the ENUM type object
blog_status_type = sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="blogstatus")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    blog_status_type.create(op.get_bind())
    op.add_column(
        "blogs",
        sa.Column(
            "status", blog_status_type, nullable=False, server_default="PUBLISHED"
        ),
    )
    op.alter_column("blogs", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blogs", "status")
    # ### end Alembic commands ###
