"""Make Token.expiry_time timezone-aware and non-nullable

Revision ID: fef5b64d336f
Revises: cea4d948af0d
Create Date: 2025-09-26 11:29:31.090010

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fef5b64d336f"
down_revision = "cea4d948af0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tokens",
        "expiry_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tokens",
        "expiry_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###
